title: Leonardo Werneck
description: PhD Candidate
institution: University of São Paulo, Brazil
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky
markdown: kramdown
kramdown:
  math_engine: mathjax
