title: Leonardo Werneck
description: Postdoc fellow
institution: University of Idaho, ID, USA
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky
markdown: kramdown
kramdown:
  math_engine: mathjax
