title: Leonardo Werneck
description: Postdoc fellow
institution: West Virginia University, WV, USA
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky
markdown: kramdown
kramdown:
  math_engine: mathjax
